### PR TITLE
bug: fix regression preventing `-trimpath` and trim of debug symbols

### LINKED ISSUE #181: xcaddy v0.3.5 vs v0.4.0 = 15mb increase in filesize on windows
What caused such huge amount of increased file size, I'm mean caddy is already beautiful small in size for what it can achieve.

But was just wondering..

RHXOhzt

### PR DESCRIPTION
**Pull request by mohammed90**
Fixes #181 

I haven't validated it yet. I might need to split `-tags` from `nobadger`.

### CODE REVIEW

**Comment by mohammed90** [comment]
@wazerstar try the CI artifacts here: https://github.com/caddyserver/xcaddy/actions/runs/8971616569?pr=182

File: builder.go [hunk 1]
```diff
@@ -131,6 +131,7 @@ func (b Builder) Build(ctx context.Context, outputFile string) error {
 			cmd.Args = append(cmd.Args,
 				"-ldflags", "-w -s", // trim debug symbols
 				"-trimpath",
+				"-tags nobadger",
```
Comment (mholt) [inline builder.go:134]:
```suggestion
				"-tags", "nobadger",
```

:grin:

**Comment by wazerstar** [comment]
Tested
45a8QrY



```
2024/05/06 17:59:27 [INFO] absolute output file path: C:\Users\Denni\Desktop\xcaddy\caddy.exe
2024/05/06 17:59:27 [INFO] Temporary folder: C:\Users\Denni\AppData\Local\Temp\buildenv_2024-05-06-1759.791475689
2024/05/06 17:59:27 [INFO] Writing main module: C:\Users\Denni\AppData\Local\Temp\buildenv_2024-05-06-1759.791475689\main.go
package main

import (
        caddycmd "github.com/caddyserver/caddy/v2/cmd"

        // plug in Caddy modules here
        _ "github.com/caddyserver/caddy/v2/modules/standard"
)

func main() {
        caddycmd.Main()
}
2024/05/06 17:59:27 [INFO] Initializing Go module
2024/05/06 17:59:27 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod init caddy
go: creating new go.mod: module caddy
go: to add module requirements and sums:
        go mod tidy
2024/05/06 17:59:27 [INFO] Pinning versions
2024/05/06 17:59:27 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe get -d -v github.com/caddyserver/caddy/v2@master
go: added github.com/beorn7/perks v1.0.1
go: added github.com/caddyserver/caddy/v2 v2.8.0-beta.1.0.20240502000919-7e2510ef43d3
go: added github.com/caddyserver/certmagic v0.20.1-0.20240423172519-140a6fa9202e
go: added github.com/caddyserver/zerossl v0.1.2
go: added github.com/cespare/xxhash/v2 v2.2.0
go: added github.com/go-task/slim-sprig v0.0.0-20230315185526-52ccab3ef572
go: added github.com/google/pprof v0.0.0-20231212022811-ec68065c825e
go: added github.com/google/uuid v1.6.0
go: added github.com/klauspost/cpuid/v2 v2.2.7
go: added github.com/libdns/libdns v0.2.2
go: added github.com/mholt/acmez/v2 v2.0.0-beta.2
go: added github.com/miekg/dns v1.1.58
go: added github.com/onsi/ginkgo/v2 v2.13.2
go: added github.com/prometheus/client_golang v1.19.0
go: added github.com/prometheus/client_model v0.5.0
go: added github.com/prometheus/common v0.48.0
go: added github.com/prometheus/procfs v0.12.0
go: added github.com/quic-go/qpack v0.4.0
go: added github.com/quic-go/quic-go v0.43.0
go: added github.com/zeebo/blake3 v0.2.3
go: added go.uber.org/mock v0.4.0
go: added go.uber.org/multierr v1.11.0
go: added go.uber.org/zap v1.27.0
go: added go.uber.org/zap/exp v0.2.0
go: added golang.org/x/crypto v0.22.0
go: added golang.org/x/exp v0.0.0-20240325151524-a685a6edb6d8
go: added golang.org/x/mod v0.16.0
go: added golang.org/x/net v0.24.0
go: added golang.org/x/sys v0.19.0
go: added golang.org/x/term v0.19.0
go: added golang.org/x/text v0.14.0
go: added golang.org/x/time v0.5.0
go: added golang.org/x/tools v0.19.0
go: added google.golang.org/protobuf v1.33.0
2024/05/06 17:59:28 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe get -d -v
2024/05/06 17:59:30 [INFO] Build environment ready
2024/05/06 17:59:30 [INFO] Building Caddy
2024/05/06 17:59:30 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod tidy -e
2024/05/06 17:59:31 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe build -o C:\Users\Denni\Desktop\xcaddy\caddy.exe -ldflags -w -s -trimpath -tags nobadger
2024/05/06 17:59:37 [INFO] Build complete: .\caddy.exe
2024/05/06 17:59:37 [INFO] Cleaning up temporary folder: C:\Users\Denni\AppData\Local\Temp\buildenv_2024-05-06-1759.791475689
```
